language: go
sudo: false
env:
  global:
  - GIT_AUTHOR_NAME: travis-ci
  - GIT_COMMITTER_NAME: ${GIT_AUTHOR_NAME}
  - GIT_AUTHOR_EMAIL: derektamsen@users.noreply.github.com
  - GIT_COMMITTER_EMAIL: ${GIT_AUTHOR_EMAIL}
  - REPO: derektamsen.github.io
  - GH_REPO: github.com/derektamsen/${REPO}.git
  - DEPLOY_BRANCH: master
  - secure: dkzF8bOFOz4OGFHtwmDgRQffwA4Cvosup6cJ3+cJX0XQd29GPoK0Fqjn6If7bRv7M++07IHww3TSVueu0Tx+8D7ButXnqIufbUM2N0ALkEHJAYNLMYql0YsZ4iww9Q7cGSOEQZJQi6T9O29h3CZi4ypVK5JKzSjvSmHHdmNKwig=
notifications:
  email:
    on_failure: always
git:
  submodules: false
  depth: 1
addons:
  apt:
    packages:
    - python-pygments
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
install:
  - go get -v github.com/spf13/hugo
script:
  - hugo version
  - hugo check --verbose
after_success:
  - if [ "${TRAVIS_BRANCH}" != "${DEPLOY_BRANCH}" ]; then echo "Not deploying from ${DEPLOY_BRANCH}"; exit 0; fi
  - if [ "${TRAVIS_PULL_REQUEST}" != 'false' ]; then echo "Not deploying from PR"; exit 0; fi
  - hugo
  - git clone "https://${GH_REPO}"
  - cp -R public/* ${REPO}
  - pushd "${REPO}"
  - git remote
  - git add -A :/
  - git commit --allow-empty -m "Publishing ${TRAVIS_COMMIT} via ${GIT_AUTHOR_NAME}"
  - git push "https://${GH_TOKEN}@${GH_REPO}" ${DEPLOY_BRANCH} > /dev/null 2>&1
  - popd
