language: generic
dist: xenial

notifications:
  email:
    on_failure: always

addons:
  apt:
    packages:
      - python3-pygments
  snaps:
    - hugo

script:
  - hugo version
  - hugo check --verbose

after_success:
  - hugo --verbose

deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: N5R8A3p5Eb9zvxN4lJyR3wGvUWsXiociimaIqYhph+7fd/9SQKAREW2Oz7YU+UWzXmFd420RdRrzQv+lwjms9kiuh3Z6vKO4ffFTnpVu0TBVKJfimKegZpTHgU3rmbTwMRcLGJCgkcERLQ5YHrQWcJLI5eHe1OEFrqEHe1ihy7g=
  on:
    branch: master
