language: go
sudo: false
notifications:
  email:
    on_failure: always
addons:
  apt:
    packages:
    - python3-pygments
    - jq
before_install:
- export HUGO_TYPE="Linux-64bit.tar.gz"
- export HUGO_URL=$(curl -fL 'https://api.github.com/repos/gohugoio/hugo/releases/latest' | jq -r ".assets[] | select(.name | test(\"${HUGO_TYPE}\")) | .browser_download_url")
- wget -O hugo_latest.tar.gz "${HUGO_URL}"
install:
- tar -xzvf hugo_latest.tar.gz -C /tmp hugo
script:
- /tmp/hugo version
- /tmp/hugo check --verbose
after_success:
- /tmp/hugo --verbose
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: HRFxcbVBIqHu6d87rHIzWZamxqwdg2prC9udCgCOCCWFdt3FpVg+TIGIYJVsLTW5I8nWVcuxN0JnovM3VT/npXyt0Mi9FGCyyPGjhCVcAUNd6CrrCFM1WuhMTiS9KJiN0FUXjBzWOzCKvdNIlZqf3yV7iQuyIHJo7GsoUonBDDk=
  on:
    branch: master
