language: go
sudo: false

notifications:
  email:
    on_failure: always

addons:
  apt:
    packages:
    - python3-pygments

install:
  - go get -v github.com/spf13/hugo

script:
  - hugo version
  - hugo check --verbose

after_success:
  - hugo --verbose

deploy:
  provider: firebase
  token:
    secure: "emITZIinUQFtwGx//Ef9Rc1BHKO4XRNNSmxVatMkJ8PudZqi7aRpXpoG2xT2+Jali5ljHDgC/54Cy5s5DeDB83ZId2RHe8lcJVHWjv4EEBBSNXGGuH7BDaDAR5DtFvh6byUclsQ3nP0s9AxrzHD1c+iEU9AN+XfR2VmstNMUgIk="
  on:
    branch: master
