language: go
sudo: false
notifications:
  email:
    on_failure: always
addons:
  apt:
    packages:
    - python3-pygments
    - snapd
install:
- snap install hugo
script:
- hugo version
- hugo check --verbose
after_success:
- hugo --verbose
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: HRFxcbVBIqHu6d87rHIzWZamxqwdg2prC9udCgCOCCWFdt3FpVg+TIGIYJVsLTW5I8nWVcuxN0JnovM3VT/npXyt0Mi9FGCyyPGjhCVcAUNd6CrrCFM1WuhMTiS9KJiN0FUXjBzWOzCKvdNIlZqf3yV7iQuyIHJo7GsoUonBDDk=
  on:
    branch: master
