baseurl = "/"
languageCode = "en-us"
title = "devops Derek"
theme = "hello-friend"
paginate = 8
enableRobotsTXT = true
# Add your disqus shortname for comments
disqusShortname = "devopsderek"
# Enable Google Analytics be inserting your tracking code
googleAnalytics = "UA-35931506-1"

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # "light" or "dark"
  defaultTheme = "light"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 3
  # Show reading time in minutes for posts
  showReadingTime = false
  # 404 page text
  pageNotFoundTitle = "Page not found"

[permalinks]
  # Optional. Change the permalink format for the 'post' content type.
  # The format shown here is the same one Jekyll/Octopress uses by default.
  posts = "/blog/:year/:month/:day/:title/"

[languages]
  [languages.en]
    title = "devops Derek"
    subtitle = "IT - Devops - Linux - /dev/urandom"
    keywords = "it,devops,linux,cloud,kubernetes"
    copyright = "Derek Tamsen"
    menuMore = "Show more"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"

    [languages.en.params.logo]
      logoText = "devops Derek - /dev/urandom"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    # [languages.en.menu]
    #   [[languages.en.menu.main]]
    #     identifier = "feed"
    #     name = "Feed"
    #     url = "/index.xml"
    #     weight = -50
