BaseUrl= "http://www.devopsderek.com/"
LanguageCode= "en-us"
Title= "devops Derek"
paginate = 5
DisqusShortname = "devopsderek"
Copyright = "&copy; <script>document.write(new Date().getFullYear())</script> Derek Tamsen"
theme = "casper"

[params]
  description = "Welcome to my blog about IT, Devops, Linux, and other things"
  cover = "images/cover_ggbridge.png"
  author = "Derek Tamsen"
  authorlocation = "San Francisco, CA"
  authorwebsite = "http://www.devopsderek.com/"
  bio = "I’m a nerd who enjoys the inner workings of devops."
  logo = "images/author_derektamsen.png"
  googleAnalyticsUserID = "UA-35931506-1"
  githubName = "derektamsen"
  twitterName = "derektamsen"
  linkedinName = "derektamsen"
  hideHUGOSupport = false

[author]
  name = "Derek Tamsen"

[permalinks]
  # Optional. Change the permalink format for the 'post' content type.
  # The format shown here is the same one Jekyll/Octopress uses by default.
  post = "/blog/:year/:month/:day/:title/"

[indexes]
  # Optional. Use if you want tags and lists.
  tag = "tags"
