BaseUrl= "http://devopsderek.com"
LanguageCode= "en-US"
Title= "devops Derek"
paginate = 5
DisqusShortname = "devopsderek"
Copyright = "&copy; Derek Tamsen"
theme = "casper"

[params]
  description = "Welcome to my blog about IT, Devops, Linux, and other things"
  # cover = "images/cover.jpg"
  author = "Derek Tamsen"
  authorlocation = "San Francisco, CA"
  authorwebsite = "http://devopsderek.com"
  bio= "my bio"
  # logo = "https://www.gravatar.com/avatar/1524b9dd15729824379a5f9fb47db32e?s=200"
  googleAnalyticsUserID = "UA-35931506-1"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  githubName = "derektamsen"
  twitterName = "derektamsen"
  linkedinName = "derektamsen"
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false

[author]
  name = "Derek Tamsen"

[permalinks]
  # Optional. Change the permalink format for the 'post' content type.
  # The format shown here is the same one Jekyll/Octopress uses by default.
  post = "/blog/:year/:month/:day/:title/"

[indexes]
  # Optional. Use if you want tags and lists.
  category = "tags"
