baseURL = "/"
languageCode = "en-us"
title = "devops Derek"
theme = "terminal"
paginate = 8
enableRobotsTXT = true
# Add your disqus shortname for comments
disqusShortname = "devopsderek"
# Enable Google Analytics be inserting your tracking code
googleAnalytics = "UA-35931506-1"

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "blue"
  # show selector to switch language
  showLanguageSelector = false
  # set theme to full screen width
  fullWidthTheme = false
  # center theme with default width
  centerTheme = true
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 3
  favicon = "img/favicon.png"
  # 404 page text
  pageNotFoundTitle = "Page not found"

[permalinks]
  # Optional. Change the permalink format for the 'post' content type.
  # The format shown here is the same one Jekyll/Octopress uses by default.
  posts = "/blog/:year/:month/:day/:title/"

[languages]
  [languages.en]
    languageName = "English"
    title = "devops Derek"
    subtitle = "IT - Devops - Linux - /dev/urandom"
    keywords = "it,devops,linux,cloud,kubernetes"
    copyright = 'This work by <a xmlns:cc="http://creativecommons.org/ns#" href="https://www.devopsderek.com/" property="cc:attributionName" rel="cc:attributionURL">Derek Tamsen</a> is licensed under <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0</a>'
    menuMore = "Show more"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"

    [languages.en.params.logo]
      logoText = "devops Derek - /dev/urandom"
      logoHomeLink = "/"

[outputs]
  home = [ "HTML", "RSS", "JSON"]
