baseurl = "https://www.devopsderek.com/"
languageCode = "en-us"
title = "devops Derek"
theme = "harbor"
paginate = 8
enableRobotsTXT = true
disqusShortName = "devopsderek"
googleAnalytics = "UA-35931506-1"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

[Author]
  name = "Derek Tamsen"

[permalinks]
  # Optional. Change the permalink format for the 'post' content type.
  # The format shown here is the same one Jekyll/Octopress uses by default.
  post = "/blog/:year/:month/:day/:title/"

[[params.nav]]
  identifier = "about"
  name = "About"
  icon = "fas fa-user fa-lg"
  url = "/about/"
  weight = 3

[[params.nav]]
  identifier = "tags"
  name = "Tags"
  icon = "fas fa-tag fa-lg"
  url = "tags"
  weight = 3

[[params.nav]]
  identifier = "search"
  name = "Search"
  icon = "fas fa-search fa-lg"
  url = "search"
  weight = 3

[[params.social]]
  name = "github"
  url = "https://github.com/derektamsen"
  icon = "fab fa-github"

[[params.social]]
  name = "twitter"
  url = "https://twitter.com/derektamsen"
  icon = "fab fa-twitter"

[outputs]
  section = [ "HTML", "RSS", "JSON"]
