#!/bin/sh

echo -e "\033[0;32mDeploying updates to Firebase...\033[0m"

# Clean the old public directory
rm -r public

# Build the project.
hugo # if using a theme, replace by `hugo -t <yourtheme>`

# Deploy updates to firebase
firebase deploy
