baseURL = 'https://www.devopsderek.com/'
languageCode = 'en-us'
title = 'devops Derek'
copyright = 'This work is licensed under CC BY-SA 4.0'

enableRobotsTXT = true

[module]
[[module.imports]]
path = "github.com/tomfran/typo/v2"

[taxonomies]
  tag = 'tags'

[permalinks]
  [permalinks.page]
    # The format shown here is the same one Jekyll/Octopress uses by default.
    posts = '/posts/:year/:month/:day/:title/'
  [permalinks.section]
    posts = '/posts/'

[params]
  # Meta description
  description = 'A Tech Blog'

  # Appearance settings
  theme = 'auto'
  colorPalette = 'catpuccin'
  hideHeader = false

  # Intro on main page, content is markdown
  homeIntroTitle = 'Welcome!'
  homeIntroContent = """
  devops Derek is a place to keep notes related to things I am working on. It
  makes it easier to later `grep -iR something_I_did_in_the_past ./`. Hopefully,
  it is also useful to others.
  """

  # Page footer
  showFooter = true
  footerContent = """
  **Derek Tamsen** | This work is licensed under [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/?ref=chooser-v1) | _Powered by [Hugo](https://gohugo.io) with theme by [tomfran/typo](https://github.com/tomfran/typo)_
  """

  # Collection to display on home
  homeCollectionTitle = 'Posts'
  homeCollection = 'posts'

  # Lists parameters
  paginationSize = 100
  listSummaries = true
  listDateFormat = 'Jan 2, 2006'

  # Breadcrumbs
  [params.breadcrumbs]
  enabled = true
  showCurrentPage = true
  home = "Home"

  # Giscus comments
  [params.giscus]
  enable = true
  repo = 'derektamsen/derektamsen.github.io-hugo'
  repoid = 'MDEwOlJlcG9zaXRvcnkyOTEyNjEyMw=='
  category = 'Post Comments'
  categoryid = 'DIC_kwDOAbxt684CjJ8V'
  mapping = 'pathname'
  theme = 'preferred_color_scheme'

  [params.author]
  email = 'dtamsen+blog@gmail.com'
  name = 'Derek Tamsen'

  # Social icons
  [[params.social]]
    name = 'bluesky'
    url = 'https://bsky.app/profile/devopsderek.com'

  [[params.social]]
    name = 'github'
    url = 'https://github.com/derektamsen'

  [[params.social]]
    name = 'linkedin'
    url = 'https://www.linkedin.com/in/derektamsen/'

  # Main menu pages
  [[params.menu]]
    name = 'home'
    url = '/'

  [[params.menu]]
    name = 'posts'
    url = '/posts'

  [[params.menu]]
    name = 'about'
    url = '/about'

# Syntax highligth on code blocks
[markup]
  [markup.highlight]
  style = 'catppuccin-frappe'
