[build.environment]
  HUGO_VERSION = "0.88.1"

[context.deploy-preview]
  command = "hugo -b $DEPLOY_PRIME_URL/"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    cache-control = '''
    max-age=7200'''

[[headers]]
  for = "/*.jpeg"
  [headers.values]
    cache-control = '''
    max-age=7200'''

[[headers]]
  for = "/*.gif"
  [headers.values]
    cache-control = '''
    max-age=7200'''

[[headers]]
  for = "/*.png"
  [headers.values]
    cache-control = '''
    max-age=7200'''

[[redirects]]
  from = "https://devopsderek.netlify.com/*"
  to = "https://www.devopsderek.com/:splat"
  status = 301
  force = true
